# serverless.yml

service: bakwan

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1

plugins:
  - serverless-offline

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'